[package]
authors = ["Pietro Brenna <pietrobrenna@hotmail.it>"]
name = "ep"
version = "0.1.0"
[dependencies]
ctrlc = "3.1.1"
num = "*"
num-iter = "*"
num-traits = "*"
pbr = "1.0.1"
rand = "0.5.5"

[dependencies.spiril]
path = "../spiril"

[profile.release]
debug = true
