[package]
name = "ep"
version = "0.1.0"
authors = ["Pietro Brenna <pietrobrenna@hotmail.it>"]

[dependencies]
spiril = { path = "./spiril" }
rand = "0.5.5"
pbr = "1.0.1"
ctrlc = "3.1.1"

[profile.release]
debug = true
